# -- global settings -----------------------------------------------------------

cpu: &NumCores 8
memory: &Memory 16G

# -- templates -----------------------------------------------------------------

environment_template: &EnvironmentTemplate
  env:
    CAF_NUM_CORES: *NumCores

resources_template: &ResourcesTemplate
  cpu: *NumCores
  memory: *Memory

windows_build_template: &WindowsBuildTemplate
  build_script: |
    set PATH=%PATH%;C:\Program Files\CMake\bin
    mkdir build
    cd build
    cmake -A x64 -DOPENSSL_ROOT_DIR="C:\Program Files\OpenSSL-Win64" ..
    cmake --build . --config %CAF_BUILD_TYPE% -- -m:%CAF_NUM_CORES%
  test_script: |
    cd build
    ctest --config %CAF_BUILD_TYPE% --output-on-failure

unix_build_template: &UnixBuildTemplate
  build_script: |
    if command -v cmake3 >/dev/null 2>&1 ; then
      CMakeCommand="cmake3"
    else
      CMakeCommand="cmake"
    fi
    mkdir build
    cd build
    $CMakeCommand -DCMAKE_BUILD_TYPE=$CAF_BUILD_TYPE ..
    $CMakeCommand --build . --parallel $CAF_NUM_CORES
  test_script: |
    if command -v ctest3 >/dev/null 2>&1 ; then
      CTestCommand="ctest3"
    else
      CTestCommand="ctest"
    fi
    cd build
    $CTestCommand --output-on-failure

# -- FreeBSD builds ------------------------------------------------------------

task:
  freebsd_instance:
    image_family: freebsd-12-1
    << : *ResourcesTemplate
  prepare_script: |
    env ASSUME_ALWAYS_YES=YES pkg bootstrap
    pkg install -y git cmake
  matrix:
    - name: "freebsd:debug"
      << : *UnixBuildTemplate
      env:
        CAF_BUILD_TYPE: Debug
    - name: "freebsd:release"
      << : *UnixBuildTemplate
      env:
        CAF_BUILD_TYPE: Release
  << : *EnvironmentTemplate

# -- Windows builds ------------------------------------------------------------

task:
  windows_container:
    image: cirrusci/windowsservercore:cmake
    << : *ResourcesTemplate
  prepare_script: |
    choco install -y --no-progress openssl
  matrix:
    - name: "windows:debug"
      << : *WindowsBuildTemplate
      env:
        CAF_BUILD_TYPE: Debug
    - name: "windows:release"
      << : *WindowsBuildTemplate
      env:
        CAF_BUILD_TYPE: Release
  << : *EnvironmentTemplate
