# -- global settings -----------------------------------------------------------

cpu: &NumCores 8
memory: &Memory 16G

# -- templates -----------------------------------------------------------------

environment_template: &EnvironmentTemplate
  env:
    CAF_NUM_CORES: *NumCores

resources_template: &ResourcesTemplate
  cpu: *NumCores
  memory: *Memory

windows_build_template: &WindowsBuildTemplate
  build_script: |
    set PATH=%PATH%;C:\Program Files\CMake\bin
    mkdir build
    cd build
    cmake -A x64 -DOPENSSL_ROOT_DIR="C:\Program Files\OpenSSL-Win64" ..
    cmake --build . --config %CAF_BUILD_TYPE% --parallel %CAF_NUM_CORES%
  test_script: |
    cd build
    ctest --config %CAF_BUILD_TYPE% --output-on-failure

# -- UNIX builds ---------------------------------------------------------------

task:
  freebsd_instance:
    image_family: freebsd-12-1
    << : *ResourcesTemplate
  prepare_script: |
    env ASSUME_ALWAYS_YES=YES pkg bootstrap
    pkg install -y git cmake
  matrix:
    - name: "freebsd:debug"
      build_script: ./.cirrus/unix-build.sh
      test_script: ./.cirrus/unix-test.sh
      env:
        CAF_BUILD_TYPE: Debug
    - name: "freebsd:release"
      build_script: ./.cirrus/unix-build.sh
      test_script: ./.cirrus/unix-test.sh
      env:
        CAF_BUILD_TYPE: Release
  << : *EnvironmentTemplate

# -- Windows build -------------------------------------------------------------

task:
  windows_container:
    image: cirrusci/windowsservercore:cmake
    << : *ResourcesTemplate
  prepare_script: |
    choco install -y --no-progress openssl
  matrix:
    - name: "windows:debug"
      << : *WindowsBuildTemplate
      env:
        CAF_BUILD_TYPE: Debug
    - name: "windows:release"
      << : *WindowsBuildTemplate
      env:
        CAF_BUILD_TYPE: Release
  << : *EnvironmentTemplate
